export const mockAnalyticsData = {
  stats: {
    totalUsers: 27,
    totalVisitors: 3298,
    totalBookings: 456,
    bookingThisMonth: 123,
  },
  revenue: {
    paid: 123456789,
    dp: 123456,
  },
  bookings: {
    returning: 456,
    new: 123,
  },
  monthlyPatients: [
    { month: "JAN", value: 280 },
    { month: "FEB", value: 250 },
    { month: "MAR", value: 320 },
    { month: "APR", value: 380 },
    { month: "MAY", value: 350 },
    { month: "JUN", value: 320 },
    { month: "JUL", value: 400 },
    { month: "AUG", value: 420 },
    { month: "SEP", value: 380 },
    { month: "OCT", value: 450 },
    { month: "NOV", value: 480 },
    { month: "DEC", value: 500 },
  ],
  topTests: [
    { id: 1, name: "Tes IQ", percentage: 74 },
    { id: 2, name: "Tes Kepribadian", percentage: 52 },
    { id: 3, name: "Tes Bakat Minat", percentage: 36 },
  ],
  topServices: [
    { id: 1, name: "Konseling Individu", percentage: 95 },
    { id: 2, name: "Konseling Pasangan", percentage: 92 },
    { id: 3, name: "Mental Health Check-Up", percentage: 89 },
  ],
  recentPatients: [
    {
      id: 1,
      name: "Budi Santoso",
      date: "1/1/2026",
      service: "Konseling Individu",
      description: "-",
    },
    {
      id: 2,
      name: "Siti Nurhaliza",
      date: "2/1/2026",
      service: "Tes IQ",
      description: "-",
    },
    {
      id: 3,
      name: "Ahmad Dahlan",
      date: "3/1/2026",
      service: "Konseling Pasangan",
      description: "-",
    },
    {
      id: 4,
      name: "Dewi Lestari",
      date: "4/1/2026",
      service: "Tes Kepribadian",
      description: "-",
    },
    {
      id: 5,
      name: "Rudi Hartono",
      date: "5/1/2026",
      service: "Mental Health Check-Up",
      description: "-",
    },
    {
      id: 6,
      name: "Maya Putri",
      date: "6/1/2026",
      service: "Konseling Individu",
      description: "-",
    },
    {
      id: 7,
      name: "Andi Wijaya",
      date: "7/1/2026",
      service: "Tes Bakat Minat",
      description: "-",
    },
  ],
};
